"""Structural repository contracts consumed by future application services."""

import uuid
from datetime import datetime
from typing import Protocol

from turbine_guard.database.commands import (
    NewAsset,
    NewMaintenanceEvent,
    NewPrediction,
    NewSensorReading,
)
from turbine_guard.database.enums import AssetStatus
from turbine_guard.database.models import Asset, MaintenanceEvent, Prediction, SensorReading


class AssetRepositoryInterface(Protocol):
    def create(self, command: NewAsset) -> Asset: ...
    def get(self, asset_id: uuid.UUID) -> Asset | None: ...
    def get_by_external_id(self, external_id: str) -> Asset | None: ...
    def list(self, *, limit: int = 100, offset: int = 0) -> list[Asset]: ...
    def update_status(self, asset: Asset, status: AssetStatus) -> Asset: ...


class SensorReadingRepositoryInterface(Protocol):
    def insert(self, command: NewSensorReading) -> SensorReading: ...
    def insert_many(self, commands: list[NewSensorReading]) -> list[SensorReading]: ...
    def get_by_asset_cycle(self, asset_id: uuid.UUID, cycle: int) -> SensorReading | None: ...
    def history_through(self, asset_id: uuid.UUID, cycle: int) -> list[SensorReading]: ...
    def latest(self, asset_id: uuid.UUID) -> SensorReading | None: ...


class PredictionRepositoryInterface(Protocol):
    def create(self, command: NewPrediction) -> Prediction: ...
    def for_asset(self, asset_id: uuid.UUID, *, limit: int = 1000) -> list[Prediction]: ...
    def latest(self, asset_id: uuid.UUID) -> Prediction | None: ...
    def recent(self, *, since: datetime | None = None, limit: int = 100) -> list[Prediction]: ...


class MaintenanceEventRepositoryInterface(Protocol):
    def create(self, command: NewMaintenanceEvent) -> MaintenanceEvent: ...
    def for_asset(self, asset_id: uuid.UUID) -> list[MaintenanceEvent]: ...
    def latest_failure_or_maintenance(self, asset_id: uuid.UUID) -> MaintenanceEvent | None: ...
